# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.define "s1" do |s1|
    s1.vm.hostname = "s1"
    s1.vm.box = "trusty-server"
    s1.vm.network "private_network", ip: "192.168.50.2"
    s1.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  end
  config.vm.define "s2" do |s2|
    s2.vm.hostname = "s2"
    s2.vm.box = "trusty-server"
    s2.vm.network "private_network", ip: "192.168.50.3"
    s2.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  end
   config.vm.define "s3" do |s3|
    s3.vm.hostname = "s3"
    s3.vm.box = "trusty-server"
    s3.vm.network "private_network", ip: "192.168.50.4"
    s3.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  end
  
   config.vm.define "a1" do |a1|
    a1.vm.hostname = "a1"
    a1.vm.box = "trusty-server"
    a1.vm.network "private_network", ip: "192.168.50.5"
    a1.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  end
  
   config.vm.define "a2" do |a2|
    a2.vm.hostname = "a2"
    a2.vm.box = "trusty-server"
    a2.vm.network "private_network", ip: "192.168.50.6"
    a2.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  end
end