#!/usr/bin/env python
# -*- coding: latin-1 -*-

import sys
sys.path.append('inventories')
import os
from collections import OrderedDict
from custom.inventory import *
from custom.hosts import *

class MachinesInventory(Inventory): 
    def __init__(self):
     all_vars={
	 'vars': {
	    'ansible_user':'vagrant' 
	      }
	 }
     super(MachinesInventory, self).__init__(all_vars)

    def get_inventory(self):	
        hosts=get_hosts()
        host_definitions=OrderedDict(
		(
		    ('s1',hosts[0]),
		    ('s2',hosts[0]),
		    ('s3',hosts[0]),
		    ('a1',hosts[0]),
		    ('a2',hosts[0])
		))
        inventory=super(MachinesInventory, self).get_inventory()
        inventory['_meta']= {'hostvars':  host_definitions}
        inventory.update({
            'consul_servers': {
                'hosts': ['s1'],
				'vars': {
					'server_count': 1
				 }
            },
             'consul_agents': {
                'hosts': [],
				'vars': {
					'server_count': 1
				 }
            }
	     })

        return inventory
	

MachinesInventory().printInventory()
