---
- hosts: "localhost"
  name: 'deploy new version'  
  connection: local 
  tasks:     
    - shell: cd ../scripts && ./deploy_pings.sh  
    
- hosts: all
  name: 'test logs'  
  gather_facts: no
  strategy: free
  tasks:     
    - shell: docker logs {{base_name}} | tail -3
      sudo: yes
      register: logs
    - assert:
        that:
          - "'Unreachable' not in logs.stdout"
    - shell: docker network connect bridge {{base_name}} 
      sudo: yes
          
- hosts: s1
  name: 'kill consul and docker'  
  gather_facts: no
  strategy: free
  tasks:  
    - shell: killall -v consul && sleep 20
      sudo: yes
          
- hosts: all
  name: 'test'  
  gather_facts: no
  strategy: free
  tasks:         
    - shell: docker ps | grep {{base_name}}
      sudo: yes  
    - shell: docker logs {{base_name}} | tail -3
      sudo: yes
      register: logs
    - debug: var=logs
    - assert:
        that:
          - "'Unreachable' not in logs.stdout"

     