---
- hosts: "localhost"
  name: 'deploy new version'  
  connection: local 
  tasks:     
    - shell: cd ../scripts && ./deploy_pings.sh  
    
- hosts: all
  name: 'test logs'  
  gather_facts: no
  strategy: free
  tasks:     
    - shell: docker logs {{base_name}} | tail -3
      sudo: yes
      register: logs
    - assert:
        that:
          - "'Unreachable' not in logs.stdout"
          
- hosts: s1:a1:a2
  name: 'restart one server and 2 agents'  
  gather_facts: no
  strategy: free
  tasks:     
    - name: restart machines
      command: shutdown -r now "restart machine"
      async: 0
      poll: 0
      sudo: yes
      ignore_errors: true
      
    - name: Wait for server to restart
      local_action: wait_for host="{{ansible_ssh_host}}" port=22 delay=10 state=present timeout=100
    - shell: sleep  10
      delegate_to: localhost
          
- hosts: all
  name: 'test'  
  gather_facts: no
  strategy: free
  tasks:         
    - shell: docker ps | grep {{base_name}}
      sudo: yes  
    - shell: docker logs {{base_name}} | tail -3
      sudo: yes
      register: logs
    - debug: var=logs
    - assert:
        that:
          - "'Unreachable' not in logs.stdout"

     