- hosts: all
  name: gather facts
  max_fail_percentage: 1
  gather_facts: yes
  strategy: free
  sudo: yes  
  tasks:   
    - shell: uname -r
      register: kernel_version
    - get_url: url="http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.3-wily/linux-headers-4.3.0-040300_4.3.0-040300.201511020949_all.deb"  dest="/tmp/linux-headers-4.3.0-040300_4.3.0-040300.201511020949_all.deb"
      when: kernel_version.stdout != '4.3.0-040300-generic'
    - get_url: url="http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.3-wily/linux-headers-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb" dest="/tmp/linux-headers-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb"
      when: kernel_version.stdout != '4.3.0-040300-generic'
    - get_url: url="http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.3-wily/linux-image-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb" dest="/tmp/linux-image-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb"
      when: kernel_version.stdout != '4.3.0-040300-generic'
    - apt: deb=/tmp/linux-headers-4.3.0-040300_4.3.0-040300.201511020949_all.deb
      when: kernel_version.stdout != '4.3.0-040300-generic'
    - apt: deb=/tmp/linux-headers-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb
      when: kernel_version.stdout != '4.3.0-040300-generic'
    - shell: dpkg -i /tmp/linux-image-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb       
      when: kernel_version.stdout != '4.3.0-040300-generic'
    - name: restart machine
      command: shutdown -r now "kernel update"
      async: 0
      poll: 0
      ignore_errors: true
      when: kernel_version.stdout != '4.3.0-040300-generic'
      
    - name: Wait for server to restart
      local_action: wait_for host="{{ansible_ssh_host}}" port=22 delay=10 state=present timeout=100
      when: kernel_version.stdout != '4.3.0-040300-generic'   
      